baseUrl : "https://domain/path_to_flarum/"
databaseConfiguration :
    host                  : "localhost"
    database              : "flarum_database_name"
    prefix                : "flarum_table_name_prefix_"
    username              : "username"
    password              : "password"
adminUser : 
    username              : "adminuser"
    password              : "adminpassword"
    password_confirmation : "adminpassword"
    email                 : "admin@email.com"
settings : 
    uninett-auth-dataporten.client_id     : "___optional____"
    uninett-auth-dataporten.client_secret : "___optional____"
    forum_title                           : "Dataporten Test Forum"
    welcome_title                         : "Velkommen til Dataporten Test Forum"
    welcome_message                       : "Bare for testing :)"
    mail_from                             : "noreply@dataporten.dev"
    default_locale                        : "no"
    theme_colored_header                  : 1
    theme_primary_color                   : "#ed1b34"
    theme_secondary_color                 : "#010777"